services:
  api:
    build: .
    container_name: rag_api
    ports:
      - '8000:80'
    restart: 'no'

  llm:
    image: ollama/ollama
    ports:
      - '8001:11434'
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: sh -c "ollama serve & sleep 5 && ollama pull qwen2.5:3b && wait"

volumes:
  ollama_data:
